### ISSUE TITLE
Error: device plugin PreStartContainer rpc failed with err: rpc error: code = Unknown desc = not such pod with the same devices list

### ISSUE THREAD

**Issue by quietnight** [nano-gpu/nano-gpu-scheduler#10]
又一个help wanted：
我按照更新后的文档部署完之后，在部署cuda-gpu-test的时候，po的状态是CreateContainerConfigError。

describe：
  Normal   Scheduled         6m37s                   default-scheduler  Successfully assigned default/cuda-gpu-test-6754c65cb7-rmhxk to master-01
  Warning  FailedScheduling  6m37s                   default-scheduler  pod cc3ec7a2-ad73-4c0f-a69e-474b8f149ae1 is in the cache, so can't be assumed
  Normal   SandboxChanged    6m36s                   kubelet            Pod sandbox changed, it will be killed and re-created.
  Warning  Failed            4m47s (x12 over 6m37s)  kubelet            Error: device plugin PreStartContainer rpc failed with err: rpc error: code = Unknown desc = not such pod with the same devices list

schduler日志：
I1129 02:04:20.628602       1 dealer.go:288] ------------
I1129 02:04:20.654523       1 controller.go:171] begin to sync controller for pod default/cuda-gpu-test-6754c65cb7-rmhxk
I1129 02:04:20.656129       1 routes.go:70] start filter for pod default/cuda-gpu-test-6754c65cb7-rmhxk
I1129 02:04:20.656164       1 predicate.go:48] Check if the pod default/cuda-gpu-test-6754c65cb7-rmhxk can be scheduled on nodes [master-01]
I1129 02:04:20.656256       1 rater.go:100] d=[(20)],sortableDemand=[(20)], indexes=[0], resultIndexes=[0]
I1129 02:04:20.656391       1 routes.go:83] NanoGPUFilter extenderFilterResult = {"Nodes":null,"NodeNames":["master-01"],"FailedNodes":{},"Error":""}
I1129 02:04:20.657668       1 routes.go:142] start bind pod default/cuda-gpu-test-6754c65cb7-rmhxk to node master-01
I1129 02:04:20.657735       1 routes.go:143] GpuSharingBind ExtenderArgs ={cuda-gpu-test-6754c65cb7-rmhxk default cc3ec7a2-ad73-4c0f-a69e-474b8f149ae1 master-01}
I1129 02:04:20.669627       1 routes.go:70] start filter for pod default/cuda-gpu-test-6754c65cb7-rmhxk
I1129 02:04:20.669668       1 predicate.go:48] Check if the pod default/cuda-gpu-test-6754c65cb7-rmhxk can be scheduled on nodes [master-01]
I1129 02:04:20.672587       1 dealer.go:284] ------resource status after bind for default/cuda-gpu-test-6754c65cb7-rmhxk------
I1129 02:04:20.672621       1 dealer.go:286] node master-01: (80)
I1129 02:04:20.672650       1 dealer.go:288] ------------
I1129 02:04:20.672687       1 routes.go:159] extenderBindingResult = {"Error":""}
I1129 02:04:20.672768       1 rater.go:100] d=[(20)],sortableDemand=[(20)], indexes=[0], resultIndexes=[0]
I1129 02:04:20.672885       1 routes.go:83] NanoGPUFilter extenderFilterResult = {"Nodes":null,"NodeNames":["master-01"],"FailedNodes":{},"Error":""}

agent日志：
E1129 02:12:39.642396       1 server.go:114] no pod with such device list: nano-0-93:nano-0-03:nano-0-76:nano-0-09:nano-0-73:nano-0-45:nano-0-79:nano-0-38:nano-0-16:nano-0-65:nano-0-80:nano-0-31:nano-0-70:nano-0-83:nano-0-99:nano-0-84:nano-0-56:nano-0-26:nano-0-55:nano-0-20
E1129 02:12:50.643334       1 server.go:114] no pod with such device list: nano-0-31:nano-0-45:nano-0-84:nano-0-26:nano-0-99:nano-0-09:nano-0-55:nano-0-20:nano-0-03:nano-0-70:nano-0-83:nano-0-76:nano-0-80:nano-0-93:nano-0-65:nano-0-73:nano-0-56:nano-0-79:nano-0-16:nano-0-38
E1129 02:13:04.643139       1 server.go:114] no pod with such device list: nano-0-26:nano-0-99:nano-0-73:nano-0-31:nano-0-93:nano-0-45:nano-0-65:nano-0-80:nano-0-55:nano-0-83:nano-0-20:nano-0-84:nano-0-56:nano-0-76:nano-0-79:nano-0-16:nano-0-38:nano-0-09:nano-0-03:nano-0-70
E1129 02:13:18.645539       1 server.go:114] no pod with such device list: nano-0-65:nano-0-80:nano-0-93:nano-0-70:nano-0-84:nano-0-76:nano-0-45:nano-0-83:nano-0-56:nano-0-26:nano-0-99:nano-0-09:nano-0-79:nano-0-38:nano-0-03:nano-0-20:nano-0-16:nano-0-73:nano-0-31:nano-0-55

感谢！

**Comment by quietnight** [comment]
另外scheduler我用的0.3.0，agent用的0.2.0

**Comment by borgerli** [comment]
可以贴下/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint的内容吗？

**Comment by quietnight** [comment]
/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint:
{"Data":{"PodDeviceEntries":[{"PodUID":"f7a9c2bc-047e-4588-9aec-ad76ca6074c2","ContainerName":"cuda","ResourceName":"nano-gpu/gpu-percent","DeviceIDs":{"0":["nano-0-41","nano-0-67","nano-0-25","nano-0-36","nano-0-83","nano-0-99","nano-0-06","nano-0-49","nano-0-14","nano-0-92","nano-0-76","nano-0-88","nano-0-84","nano-0-42","nano-0-37","nano-0-00","nano-0-33","nano-0-13","nano-0-81","nano-0-60"]},"AllocResp":"Ch4KFk5WSURJQV9WSVNJQkxFX0RFVklDRVMSBG5vbmUKDwoDR1BVEghiMzBhODhiYwoICgJrdRICMjAaOgobL2hvc3QvZGV2L25hbm8tZ3B1LWIzMGE4OGJjEhYvZGV2L25hbm8tZ3B1LWIzMGE4OGJjGgNyd20aQAoeL2hvc3QvZGV2L25hbm8tZ3B1Y3RsLWIzMGE4OGJjEhkvZGV2L25hbm8tZ3B1Y3RsLWIzMGE4OGJjGgNyd20="}],"RegisteredDevices":{"nano-gpu/gpu-percent":["nano-0-20","nano-0-25","nano-0-33","nano-0-53","nano-0-59","nano-0-60","nano-0-12","nano-0-16","nano-0-70","nano-0-79","nano-0-10","nano-0-15","nano-0-29","nano-0-46","nano-0-50","nano-0-71","nano-0-00","nano-0-03","nano-0-72","nano-0-94","nano-0-35","nano-0-41","nano-0-47","nano-0-85","nano-0-87","nano-0-99","nano-0-23","nano-0-24","nano-0-78","nano-0-83","nano-0-66","nano-0-73","nano-0-82","nano-0-06","nano-0-57","nano-0-86","nano-0-22","nano-0-58","nano-0-28","nano-0-39","nano-0-55","nano-0-62","nano-0-17","nano-0-19","nano-0-81","nano-0-97","nano-0-27","nano-0-36","nano-0-49","nano-0-56","nano-0-67","nano-0-69","nano-0-77","nano-0-96","nano-0-02","nano-0-18","nano-0-98","nano-0-51","nano-0-75","nano-0-76","nano-0-11","nano-0-30","nano-0-37","nano-0-65","nano-0-84","nano-0-92","nano-0-04","nano-0-13","nano-0-31","nano-0-34","nano-0-42","nano-0-74","nano-0-95","nano-0-05","nano-0-09","nano-0-38","nano-0-43","nano-0-44","nano-0-48","nano-0-54","nano-0-68","nano-0-01","nano-0-07","nano-0-26","nano-0-32","nano-0-40","nano-0-45","nano-0-61","nano-0-64","nano-0-08","nano-0-21","nano-0-88","nano-0-91","nano-0-90","nano-0-14","nano-0-89","nano-0-80","nano-0-93","nano-0-52","nano-0-63"]}},"Checksum":3950054853}

**Comment by borgerli** [comment]
kubelet_internal_checkpoint里分配的设备跟PrestartContainer中的设备列表不一致，这里有可能是kubelet的bug

可以试试删掉重建pod

**Comment by quietnight** [comment]
删除重建后，分配的设备和PrestartContainer的设备列表一致了，但是依然在创建容器的过程中报not such pod with the same devices list

**Comment by borgerli** [comment]
我们在k8s 1.20及以下版本测试测试过。请问你的k8s版本是1.21.6吧？我们测试下这个版本

**Comment by borgerli** [comment]
问题已修复，需要额外的下面两个步骤：
1. nano-gpu-agent请使用0.3.0版本：https://github.com/nano-gpu/nano-gpu-agent/blob/master/deploy/nano-gpu-agent.yaml
2. 需要设置docker的默认runtime为nvidia：set nvidia as docker default-runtime: add "default-runtime": "nvidia" to /etc/docker/daemon.json, and restart docker daemon.
