### ISSUE TITLE
api/v1/namespaces/kube-system/services/nano-gpu-scheduler/proxy/scheduler/filter400

### ISSUE THREAD

**Issue by quietnight** [nano-gpu/nano-gpu-scheduler#8]
我按照Get started部署了agent和scheduler，并且把scheduler policy配置到了kube-scheduler里面。以上的步骤显示执行成功了，但当我部署文中的cuda-gpu-test的时候，它卡在了pending阶段。通过describe我看到以下事件：

Events:
  Type     Reason            Age   From               Message

  Warning  FailedScheduling  12s   default-scheduler  failed filter with extender at URL http://192.168.3.76:6443/api/v1/namespaces/kube-system/services/nano-gpu-scheduler/proxy/scheduler/filter, code 400
  Warning  FailedScheduling  11s   default-scheduler  failed filter with extender at URL http://192.168.3.76:6443/api/v1/namespaces/kube-system/services/nano-gpu-scheduler/proxy/scheduler/filter, code 400

然后查看了scheduler的日志：

I1125 03:26:06.565888       1 main.go:65] Priority algorithm is binpack
W1125 03:26:06.566008       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1125 03:26:06.567723       1 controller.go:62] Creating event broadcaster
I1125 03:26:06.588004       1 controller.go:116] begin to wait for cache
I1125 03:26:06.588025       1 controller.go:121] init the node cache successfully
I1125 03:26:06.688480       1 controller.go:127] init the pod cache successfully
I1125 03:26:06.688521       1 controller.go:130] end to wait for cache
I1125 03:26:06.688652       1 main.go:112] server starting on the port :39999
I1125 03:26:06.688684       1 controller.go:144] Starting GPU Sharing Controller.
I1125 03:26:06.688744       1 controller.go:145] Waiting for informer caches to sync
I1125 03:26:06.688763       1 controller.go:147] Starting 1 workers.
I1125 03:26:06.688798       1 controller.go:152] Started workers
I1125 05:02:16.010601       1 controller.go:171] begin to sync controller for pod default/cuda-gpu-test-6754c65cb7-cd84p

k8s version: 1.21.6
nvidia driver：407.82

我看了下代码，它在PredicateRoute这里检测了请求的body为空返回400。是什么地方配置错了吗？

**Comment by borgerli** [comment]
6443是apiserver的https地址，需要https://访问，并且配置证书。这里可以直接配置nano-gpu-scheduler服务的clusterIP地址：
{
  "urlPrefix": "http://<nano-gpu-scheduler-svc-clusterip>:39999/scheduler",
  "filterVerb": "filter",
  "prioritizeVerb": "priorities",
  "bindVerb": "bind",
  "weight": 1,
  "enableHttps": false,
  "nodeCacheCapable": true,
  "managedResources": [
    {
      "name": "nano-gpu/gpu-percent"
    }
  ]
}

我们更新下文档

**Comment by borgerli** [comment]
readme已更新
